<a href="https://colab.research.google.com/github/shoyohinata-05/Compute_task/blob/main/Compute(task2)_Aditya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

uploading the dataset

In [ ]:
df=pd.read_csv("/content/data.csv")
df

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.01020,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.19900,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.03440,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.60400,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.18000,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,2012,0.00106,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.3330,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.08770,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.1310,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.00857,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.1070,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.00164,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.1330,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.00281,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.1410,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

viewing only some initial rows

In [ ]:
df.head()

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.0102,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.1990,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.0344,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.6040,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.1800,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys

specifing the number of initial rows

In [ ]:
df.head(10)

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.01020,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.19900,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.03440,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.60400,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.18000,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys
5,5,0.00479,0.804,251333,0.560,0.000000,8,0.1640,-6.682,1,0.1850,85.023,4.0,0.264,1,Sneakin’,Drake
6,6,0.01450,0.739,241400,0.472,0.000007,1,0.2070,-11.204,1,0.1560,80.030,4.0,0.308,1,Childs Play,Drake
7,7,0.02020,0.266,349667,0.348,0.664000,10,0.1600,-11.609,0,0.0371,144.154,4.0,0.393,1,Gyöngyhajú lány,Omega
8,8,0.04810,0.603,202853,0.944,0.000000,11,0.3420,-3.626,0,0.3470,130.035,4.0,0.398,1,I've Seen Footage,Death Grips
9,9,0.00208,0.836,226840,0.603,0.000000,7,0.5710,-7.792,1,0.2370,99.994,4.0,0.386,1,Digital Animal,Honey Claws

viewing some of the ending rows

In [ ]:
df.tail()

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
2012,2012,0.00106,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.333,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.08770,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.131,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.00857,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.107,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.00164,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.133,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.00281,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.141,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

viewing some of the ending rows ,specifing the number of row as 10

In [ ]:
df.tail(10)

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
2007,2007,0.002170,0.639,296276,0.978,0.112000,11,0.0838,-2.376,1,0.0730,144.986,4.0,0.494,0,Let It Go - Scott Melker & Mister Gray Remix,NERVO
2008,2008,0.054100,0.646,160408,0.714,0.000000,0,0.1340,-6.511,1,0.0378,97.957,4.0,0.589,0,"Call On Me - EDWYNN X TIKAL, Spirix Remix",Starley
2009,2009,0.004990,0.595,224000,0.837,0.035900,1,0.1010,-6.011,1,0.0696,149.964,4.0,0.331,0,Aamon,Kuuro
2010,2010,0.002310,0.624,206013,0.971,0.121000,6,0.2550,-0.935,0,0.0643,102.003,4.0,0.442,0,Hey Baby - Steve Aoki Remix,Dimitri Vegas & Like Mike
2011,2011,0.000586,0.528,245053,0.879,0.004890,6,0.0432,-5.891,0,0.1200,128.268,4.0,0.327,0,Brightside - Borgeous Remix,Icona Pop
2012,2012,0.001060,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.3330,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.087700,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.1310,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.008570,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.1070,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.001640,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.1330,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.002810,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.1410,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

to print information of the data frame such as data type

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2017 entries, 0 to 2016
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        2017 non-null   int64
 1   acousticness      2017 non-null   float64
 2   danceability      2017 non-null   float64
 3   duration_ms       2017 non-null   int64
 4   energy            2017 non-null   float64
 5   instrumentalness  2017 non-null   float64
 6   key               2017 non-null   int64
 7   liveness          2017 non-null   float64
 8   loudness          2017 non-null   float64
 9   mode              2017 non-null   int64
 10  speechiness       2017 non-null   float64
 11  tempo             2017 non-null   float64
 12  time_signature    2017 non-null   float64
 13  valence           2017 non-null   float64
 14  target            2017 non-null   int64
 15  song_title        2017 non-null   object
 16  artist            2017 non-null   object
dtypes: float64(10), int64(5), object(2)
memory usage: 268.0+ KB

 to sort values in danceability column and then attaching song title to the respective rows

In [ ]:
df.sort_values('danceability')['song_title'].head(10)

729                                            Bumpy Road
532                                       Wake Bake Skate
817     Mozart: Requiem in D Minor, K. 626: VIII. Lacr...
1600           Trio Sonata in G Major, Wq. 144: I. Adagio
1598    Piano Quartet in E flat, Op.47: 3. Andante can...
522                                                 Outro
1348                 Be My Valentine (feat. Dickie Allen)
1464                                           Right Here
1313                                      Senseless Order
1306                                                 Ruin
Name: song_title, dtype: object

attaching artist column also and showing only initial 10 rows

In [ ]:
df.sort_values('danceability')[['song_title', 'artist']].head(10)

,song_title,artist
729,Bumpy Road,Destruction Unit
532,Wake Bake Skate,FIDLAR
817,"Mozart: Requiem in D Minor, K. 626: VIII. Lacr...",Nikolaus Harnoncourt
1600,"Trio Sonata in G Major, Wq. 144: I. Adagio",Carl Philipp Emanuel Bach
1598,"Piano Quartet in E flat, Op.47: 3. Andante can...",Robert Schumann
522,Outro,M83
1348,Be My Valentine (feat. Dickie Allen),Brojob
1464,Right Here,Keys N Krates
1313,Senseless Order,Signs of the Swarm
1306,Ruin,Altered Perceptions

sorting the values based on duration_ms and printing there respective song name , srtidt and value

In [ ]:
df.sort_values('duration_ms')[['song_title', 'artist', 'duration_ms']].tail(10)

,song_title,artist,duration_ms
1602,"String Quintet in C Major, Op. 29: II. Adagio ...",Ludwig van Beethoven,649415
304,Night on Bald Mountain,Modest Mussorgsky,659560
858,Night on Bald Mountain,Modest Mussorgsky,700027
404,Who Is He And What Is He To You,Creative Source,703107
335,Zombie,Fela Kuti,745653
1565,Gloomy Sunday,Branford Marsalis,763467
1603,Viola Sonata in C Minor: III. Andante con vari...,Felix Mendelssohn,784013
819,Southern Man - Live,"Crosby, Stills, Nash & Young",825027
695,Music Is the Answer - Original Extended 12-Inc...,Celeda,849960
1535,The Nearness of You,Joshua Redman,1004627

adding a filter to duration_ms such that it only shows rows with duration less than 400000 ms

In [ ]:
df_filt = df[df['duration_ms'] < 400000] #Our first filter in action
df_filt

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.01020,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.19900,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.03440,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.60400,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.18000,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,2012,0.00106,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.3330,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.08770,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.1310,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.00857,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.1070,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.00164,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.1330,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.00281,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.1410,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

# **Activities to sharpen** **skills**

adding a filter to duration_ms such that it only shows rows with energy greater than 0.4

In [ ]:
df_1 = df[df['energy'] > 0.4 ]
df_1[['song_title','energy']]

                                song_title  energy
0                                 Mask Off   0.434
2                             Xanny Family   0.412
4                           Parallel Lines   0.561
5                                 Sneakin’   0.560
6                              Childs Play   0.472
...                                    ...     ...
2012   Like A Bitch - Kill The Noise Remix   0.932
2013                                 Candy   0.892
2014  Habit - Dack Janiels & Wenzday Remix   0.935
2015                         First Contact   0.992
2016                    I Wanna Get Better   0.915

[1830 rows x 2 columns]

ascending=False means we are sorting them in  descending order

In [ ]:
df_2 = df[df['duration_ms'] > 300000 ]
b=df_2.sort_values('tempo', ascending=False)
b.head(10)[['song_title','artist','duration_ms','tempo']]

,song_title,artist,duration_ms,tempo
412,Lazuli,Beach House,301867,219.331
942,Remember,Gino Soccio,395200,186.328
729,Bumpy Road,Destruction Unit,377177,185.906
1560,Emperor Jones - Instrumental,Joe Lovano,314493,184.007
992,Swerve... the reeping of all that is worthwhil...,Shabazz Palaces,310187,174.062
4,Parallel Lines,Junior Boys,392893,174.004
214,Blood On The Leaves,Kanye West,359800,171.893
1090,"Sola (Remix) [feat. Daddy Yankee, Wisin, Farru...",Anuel Aa,307910,169.801
712,Stoned and Starving,Parquet Courts,311680,169.792
1520,Mommy's Shawl,Yelena Eckemoff,305427,162.892

In [ ]:
df_3 = df[df['energy'] > 0.5 ]
c=df_3[df['artist']== 'Drake']
c

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
5,5,0.00479,0.804,251333,0.560,0.000000,8,0.1640,-6.682,1,0.1850,85.023,4.0,0.264,1,Sneakin’,Drake
37,37,0.05650,0.853,205879,0.547,0.000000,1,0.3410,-7.535,1,0.1940,142.065,4.0,0.677,1,Jumpman,Drake
117,117,0.00257,0.896,267024,0.623,0.000258,2,0.0390,-8.008,1,0.0571,134.962,4.0,0.564,1,Hotline Bling,Drake
154,154,0.00157,0.790,217707,0.676,0.000000,8,0.2500,-6.432,0,0.2710,132.002,4.0,0.314,1,Big Rings,Drake
440,440,0.36900,0.662,236733,0.571,0.000197,6,0.0908,-7.382,0,0.1060,152.009,4.0,0.442,1,Headlines,Drake
589,589,0.04250,0.790,173160,0.531,0.000000,8,0.2660,-6.968,1,0.1970,86.306,4.0,0.498,1,Started From the Bottom,Drake
779,779,0.76300,0.707,275227,0.709,0.000000,11,0.2740,-3.979,0,0.3400,89.094,4.0,0.497,1,0 To 100 / The Catch Up,Drake
1016,1016,0.01030,0.745,143214,0.822,0.000004,7,0.1550,-6.354,1,0.2520,86.733,5.0,0.374,1,Skepta Interlude,Drake
1218,1218,0.21900,0.427,257760,0.861,0.000000,1,0.2770,-4.874,1,0.3760,161.776,4.0,0.581,0,Best I Ever Had,Drake
1223,1223,0.04310,0.697,277387,0.527,0.000013,0,0.0882,-10.438,0,0.2110,121.849,4.0,0.289,0,Take Care,Drake

In [ ]:
c[['song_title','energy']]

                   song_title  energy
5                    Sneakin’   0.560
37                    Jumpman   0.547
117             Hotline Bling   0.623
154                 Big Rings   0.676
440                 Headlines   0.571
589   Started From the Bottom   0.531
779   0 To 100 / The Catch Up   0.709
1016         Skepta Interlude   0.822
1218          Best I Ever Had   0.861
1223                Take Care   0.527

# Extra questions

In [ ]:
z=df.sort_values('instrumentalness',ascending=False)[['song_title', 'artist', 'instrumentalness']]
z

,song_title,artist,instrumentalness
1313,Senseless Order,Signs of the Swarm,0.976
271,So Destroyed (channeling Rage Peace),Prince Rama,0.968
1575,A Hundred Dreams from Now,Ray Bryant,0.964
1619,Raven,John Dahlbäck,0.958
725,Strandbar (disko),Todd Terje,0.957
...,...,...,...
1421,Trap Trap Trap,Rick Ross,0.000
1422,Dead Presidents,Rick Ross,0.000
1423,She On My Dick,Rick Ross,0.000
1424,I Think She Like Me,Rick Ross,0.000
1008,Toothache,Jaykae,0.000

In [ ]:
p=df[['artist']].value_counts('artist').head(10)
p=p.index.tolist()
p

['Drake',
 'Rick Ross',
 'Disclosure',
 'Backstreet Boys',
 'WALK THE MOON',
 'FIDLAR',
 'Crystal Castles',
 '*NSYNC',
 'Fall Out Boy',
 'Michael Jackson']

In [ ]:
gk = df.groupby('artist')['tempo'].mean()
gk[p]

artist
Drake              112.406750
Rick Ross          110.721923
Disclosure         128.118417
Backstreet Boys    113.066600
WALK THE MOON      136.163600
FIDLAR             145.983444
Crystal Castles    128.600778
*NSYNC             140.488375
Fall Out Boy       133.815625
Michael Jackson    119.923250
Name: tempo, dtype: float64